### ISSUE TITLE
BUG007# เมื่อค้นหาปีตรวจ, เดือนตรวจ Report การตอบกลับแสดงไม่เหมือน Report เดิม

### ISSUE THREAD

**Issue by Sun1212312121** [Sun1212312121/IAMS_2024#7]
![Image](https://github.com/user-attachments/assets/82dc763c-a1d3-4677-a08b-1cb0149a7507)
![Image](https://github.com/user-attachments/assets/008c3cbe-2eb4-4475-ad0e-27eefc9ec5ef)
![Image](https://github.com/user-attachments/assets/4c260157-74bf-4a02-9be2-c951aeb2c598)

**Comment by failogun** [comment]
อันนี้ไม่ตรงเพระาว่า รายงานใหม่ถ้าไม่มี Comment Issue ก็จะไม่ดึงมาแสดงครับ

**Comment by Sun1212312121** [comment]
หลังจากนำ version นี้ขึ้นไปแล้ว ถ้าเจ้าหน้าที่ Audit จะดู Report ที่มีการเข้าตรวจของเดิมจะไม่สามารถเห็นข้อมูล Report การตอบกลับได้ รวบกวน owner Comfirm กับ User

**Comment by Sun1212312121** [comment]
owner ทำการดึงข้อมูลจาก Production มาให้บน UAT  QA ตรวจสอบแล้วข้อมูลเท่ากันทั้ง Report เก่าและReport ตอบกลับ
[20241001_1600520360.xlsx](https://github.com/user-attachments/files/17202881/20241001_1600520360.xlsx)
[20241001_1600520365_audcomment.xlsx](https://github.com/user-attachments/files/17202882/20241001_1600520365_audcomment.xlsx)
